#!/bin/bash

if [ $# -ne 3 ]
then
    echo "Please pass three arguments, otherwise the script will not work."
    exit 1
fi

if [ $1 -gt $2 ] && [ $1 -gt $3 ]
then
    echo "$1 is greater among the three numbers."
elif [ $2 -gt $1 ] && [ $2 -gt $3 ]
then
    echo "$2 is greater among the three numbers."
else
    echo "$3 is greater among the three numbers."
fi

